# Explicitly set none for repositry trigger
trigger:
- none

# weight-tracker-ci YAML pipeline
# We are setting up a pipeline resource that references the weight-tracker-ci
# pipeline and setting up a pipeline completion trigger so that our weight-tracker-cd
# pipeline runs when a run of the weight-tracker-ci pipeline completes
resources:
  pipelines:
  - pipeline: weight-tracker-ci # Name of the pipeline resource.
    source: weight-tracker-ci # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

pool:
  name: default

#add group variables
variables:
- group: webservers

stages:
- stage: Staging
  jobs:
  - deployment: Deploy
    displayName: Deploy Staging
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Ansible@0
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: $(ansible_playbook_path)
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: '$(ansible_staging_host_path)'

- stage: Production
  dependsOn: Staging
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy Production
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Ansible@0
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: $(ansible_playbook_path)
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: '$(ansible_production_host_path)'
              