
trigger:
- main

pool:
  name: default
stages:  
- stage: Build  
  jobs:  
  - job: BuildJob  
    steps:
   # Archive build   
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.Sourcesdirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/bootcamp-app.zip'
        replaceExistingArchive: true   

   # publish universak package to artifacts  
    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '4ca3c7ef-94e8-4eec-b928-dbf40834240f/685d6d3e-9c6d-42c0-b0e1-2bf79ad8a0d3'
        vstsFeedPackagePublish: 'bootcamp-app'
        versionOption: 'patch'